/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // 1. Primary Brand (Deep Navy)
        primary: {
          DEFAULT: '#0B1F33',
          dark: '#061220',
          light: '#163859',
          soft: '#23507D',
          muted: 'rgba(11, 31, 51, 0.08)',
          hover: '#163859',
          mid: '#93C5FD',
        },
        'primary-dark': '#061220',
        'primary-light': '#163859',
        'primary-soft': '#23507D',
        'primary-hover': '#163859',
        'primary-mid': '#93C5FD',

        // 2. Action & Accent (Electric Blue)
        action: {
          DEFAULT: '#2563EB',
          dark: '#1D4ED8',
          light: '#DBEAFE',
          muted: 'rgba(37, 99, 235, 0.08)',
          border: 'rgba(37, 99, 235, 0.25)',
          hover: '#1D4ED8',
        },
        'action-dark': '#1D4ED8',
        'action-light': '#DBEAFE',
        blue: {
          DEFAULT: '#2563EB',
          dark: '#1D4ED8',
          light: '#DBEAFE',
          bg: '#DBEAFE',
        },
        lightBlue: '#DBEAFE',
        blueBg: '#DBEAFE',

        // 3. Premium (Pro Arth Gold)
        gold: {
          DEFAULT: '#C89B3C',
          dark: '#92400E',
          light: '#FDF4E6',
          border: '#E5C77A',
          muted: 'rgba(200, 155, 60, 0.10)',
        },
        'gold-dark': '#92400E',
        'gold-light': '#FDF4E6',
        'gold-border': '#E5C77A',
        premium: {
          DEFAULT: '#C89B3C',
          dark: '#92400E',
          light: '#FDF4E6',
          border: '#E5C77A',
        },

        // 4. Market Bullish
        bull: {
          DEFAULT: '#16A34A',
          dark: '#15803D',
          bg: '#DCFCE7',
          glow: 'rgba(22, 163, 74, 0.18)',
        },
        'bull-dark': '#15803D',
        'bull-bg': '#DCFCE7',
        success: {
          DEFAULT: '#16A34A',
          dark: '#15803D',
          light: '#DCFCE7',
          bg: '#DCFCE7',
        },
        profit: {
          DEFAULT: '#16A34A',
          dark: '#15803D',
          light: '#DCFCE7',
          bg: '#DCFCE7',
        },
        'profit-light': '#DCFCE7',

        // 5. Market Bearish
        bear: {
          DEFAULT: '#DC2626',
          dark: '#B91C1C',
          bg: '#FEE2E2',
          glow: 'rgba(220, 38, 38, 0.18)',
        },
        'bear-dark': '#B91C1C',
        'bear-bg': '#FEE2E2',
        danger: {
          DEFAULT: '#DC2626',
          dark: '#B91C1C',
          light: '#FEE2E2',
          bg: '#FEE2E2',
        },
        loss: {
          DEFAULT: '#DC2626',
          dark: '#B91C1C',
          light: '#FEE2E2',
          bg: '#FEE2E2',
        },
        'loss-light': '#FEE2E2',

        // 6. Warnings & Hold
        warning: {
          DEFAULT: '#F59E0B',
          dark: '#D97706',
          bg: '#FEF3C7',
          light: '#FEF3C7',
        },
        'warning-dark': '#D97706',
        'warning-bg': '#FEF3C7',

        // 7. Backgrounds & Surfaces
        surface: {
          DEFAULT: '#FFFFFF',
          card: '#FFFFFF',
          bg: '#F8FAFC',
          border: '#E5E7EB',
          borderLight: '#F1F5F9',
        },
        navy: {
          DEFAULT: '#0B1F33',
          dark: '#061220',
          light: '#163859',
          soft: '#23507D',
          hover: '#061220',
        },
        'navy-hover': '#061220',
        brand: {
          primary: '#0B1F33',
          navy: '#0B1F33',
          blue: '#2563EB',
          action: '#2563EB',
          gold: '#C89B3C',
          bg: '#F8FAFC',
          card: '#FFFFFF',
          border: '#E5E7EB',
          borderLight: '#F1F5F9',
          secondary: '#64748B',
          muted: '#94A3B8',
          text: '#0F172A',
          loss: '#DC2626',
          profit: '#16A34A',
          warning: '#F59E0B',
        },
        secondary: {
          DEFAULT: '#64748B',
          light: '#F1F5F9',
          hover: '#475569',
        },
        'secondary-light': '#F1F5F9',
        muted: '#94A3B8',
        border: '#E5E7EB',
        'border-light': '#F1F5F9',

        // 8. Text Hierarchy
        textPrimary: '#0F172A',
        textSecondary: '#64748B',
        textTertiary: '#94A3B8',
        textDisabled: '#CBD5E1',

        // Dark Mode
        dark: {
          bg: '#061220',
          card: '#0B1F33',
          border: '#1E293B',
          text: '#F8FAFC',
          muted: '#94A3B8',
        }
      },
      fontFamily: {
        sans: ['TT Norms Pro', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['3rem', { lineHeight: '1.15', fontWeight: '800' }],
        'h1': ['2.25rem', { lineHeight: '1.2', fontWeight: '700' }],
        'h2': ['1.875rem', { lineHeight: '1.25', fontWeight: '700' }],
        'h3': ['1.5rem', { lineHeight: '1.3', fontWeight: '600' }],
        'body': ['1rem', { lineHeight: '1.5', fontWeight: '400' }],
        'caption': ['0.875rem', { lineHeight: '1.4', fontWeight: '400' }],
      },
      spacing: {
        '0': '0px',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
      },
      borderRadius: {
        'card': '20px',
        'button': '14px',
        'input': '14px',
        'modal': '24px',
        'chart': '16px',
      },
      boxShadow: {
        'card': '0 2px 10px rgba(11, 31, 51, 0.06)',
        'card-md': '0 4px 14px rgba(11, 31, 51, 0.08)',
        'accent': '0 6px 16px rgba(37, 99, 235, 0.20)',
        'gold': '0 6px 16px rgba(200, 155, 60, 0.20)',
        'premium-sm': '0 2px 8px -1px rgba(11, 31, 51, 0.05), 0 1px 3px -1px rgba(11, 31, 51, 0.04)',
        'premium': '0 8px 28px -4px rgba(11, 31, 51, 0.06), 0 2px 8px -2px rgba(11, 31, 51, 0.04)',
        'premium-lg': '0 20px 48px -6px rgba(11, 31, 51, 0.08), 0 8px 24px -4px rgba(11, 31, 51, 0.04)',
        'premium-xl': '0 32px 64px -12px rgba(11, 31, 51, 0.10), 0 16px 32px -8px rgba(11, 31, 51, 0.05)',
        'glow-blue': '0 0 24px 4px rgba(37, 99, 235, 0.22)',
        'glow-navy': '0 0 20px 2px rgba(11, 31, 51, 0.25)',
        'glow-green': '0 0 20px 2px rgba(22, 163, 74, 0.15)',
        'glow-gold': '0 0 20px 2px rgba(200, 155, 60, 0.25)',
      },
    },
  },
  plugins: [],
  safelist: [
    'bg-primary', 'bg-primary-light', 'bg-primary-soft', 'bg-primary-dark', 'bg-primary-hover',
    'text-primary', 'text-primary-hover', 'text-primary-light', 'text-primary-soft',
    'border-primary', 'border-primary-light', 'border-primary-soft',
    'ring-primary', 'ring-action',
    'bg-action', 'bg-action-dark', 'bg-action-light', 'text-action', 'text-action-dark', 'border-action',
    'bg-gold', 'bg-gold-dark', 'bg-gold-light', 'text-gold', 'text-gold-dark', 'border-gold',
    'bg-bull', 'bg-bull-bg', 'bg-bull-dark', 'text-bull', 'text-bull-dark',
    'bg-bear', 'bg-bear-bg', 'bg-bear-dark', 'text-bear', 'text-bear-dark',
    'bg-warning', 'bg-warning-bg', 'bg-warning-dark', 'text-warning', 'text-warning-dark',
    'bg-navy', 'bg-navy-hover', 'text-navy', 'border-navy',
    'bg-secondary', 'bg-secondary-light', 'text-secondary', 'border-secondary',
    'bg-profit', 'bg-profit-light', 'text-profit', 'bg-loss', 'bg-loss-light', 'text-loss',
    'hover:bg-primary-light', 'hover:bg-primary-hover', 'hover:text-primary',
    'from-primary', 'to-primary', 'from-primary-hover', 'to-primary-hover',
    'from-navy', 'to-navy', 'from-action', 'to-action',
    'badge-bull', 'badge-buy', 'badge-profit',
    'badge-bear', 'badge-sell', 'badge-loss',
    'badge-gold', 'badge-premium', 'badge-pro',
    'badge-action', 'badge-info', 'badge-nse',
    'badge-warning', 'badge-hold', 'badge-bse',
    'badge-neutral', 'badge-secondary',
  ],
}
